import turtle
turtle.shape('turtle')
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.penup()
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.shape('turtle')
turtle.pendown()
turtle.right(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(160)
for x in range (1,11):
    turtle.forward(100)
    turtle.backward(100)
    turtle.left(36)
